config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, :list, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(strong_bookmark)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def strong_bookmark
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(strong_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def strong_list
    params.require(:list).permit(:name, :photo)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmarks </h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "add bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Index page</h1>
<% @lists.each do |list| %>
<%= link_to list_path(list) do  %>
  <h5 class="card-title"><%= list.name %></h5>
  <div class="card-body">
    <% if list.photo.attached? %>
      <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill%>
    <% else %>
      <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU', height: 300, width: 400, crop: :fill%>
    <% end %>
  <% end %>
  <% end %>

  <%= link_to "Add a list", new_list_path,  class: "btn btn-primary m-2" %>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://image.pollinations.ai/prompt/wagon-movie-list);">
  <div class="container">
    <h1>Le Wagon Movie list!</h1>
  </div>
</div>
<div class="container mt-3">
  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do  %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://image.pollinations.ai/prompt/<%= list.name %>-movie);">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/lists/new.html.erb
<h1>New lists create page</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "submit", class: "btn btn-primary mx-4 w-50" %>
<% end %>

app/views/lists/show.html.erb
<h2 class=m-4 ><%= @list.name %></h2>
<%= link_to "Go to see all your lists", root_path, class: "btn btn-primary m-2" %>
<%= link_to "Add a bookmark", new_list_bookmark_path(@list), class: "btn btn-primary m-2"  %>
<div class="container">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card" style="width: 18rem;">
      <%= image_tag bookmark.movie.poster_url %>
      <div class="card-body">
        <h5 class="card-title"><%= bookmark.movie.title %></h5>
        <p class="card-text"><%= bookmark.movie.overview %></p>
        <h3 class=m-4 >📝<%= bookmark.comment %></h3>
        <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
      <% end %>
    </div>
  </div>
</div>



<div class="container">
  <h1><%= @list.name %></h1>
  <%= link_to "back to lists", lists_path %>
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-product my-2">
      <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title %>
      <div class="card-product-infos">
        <h2><%= bookmark.movie.title %> - ⭐️ <%= bookmark.movie.rating %></h2>
        <p><%= bookmark.movie.overview %></p>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-comment"></i><em><%= bookmark.comment %></em></p>
          <%= link_to list_bookmark_path(@list, bookmark), { data: { turbo_method: :delete, turbo_confirm: 'ok?' }} do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <p class="text-center">
    <%= link_to new_list_bookmark_path(@list) do %><i class="fa-solid fa-circle-plus"></i><% end %>
  </p>
</div>